[package]
name = "pocket_reading_list"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getpocket = "0.2.3"
tokio = "1.36.0"
